#部署注意事项：
#  1、路径配置文件等一定要对
#  2、window下配置，需要 在 C:\Users<username> 创建.wslconfig 文件，文件内容如下
#     kernelCommandLine = "sysctl.vm.overcommit_memory=1"
#  重启：wsl --shutdown


version: "3.0"      #docker-compose的版本号

networks:     #网络配置
  redis-sentinel-1:
    driver: bridge

services:           #所有服务的入口  固定写法
  redis-master:     #自定义服务名
    image: redis:6.0.9   #我们所需要运行的镜像，没有的话，会自定为我们下载
    container_name: redis-master  #镜像运行后的容器名，自定义
    ports:
      - 6379:6379           #宿主机的6379映射容器内部的6379端口
    volumes:  #目录挂载 。分号 ： 右边代表容器内部的目录，分号左边表示宿主机的目录，
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-master.conf:/redis.conf
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-master/data:/data
    command: bash -c "redis-server /redis.conf"  #容器启动后，运行的命令
    networks:
      - redis-sentinel-1

  redis-slave-1:
    image: redis:6.0.9
    container_name: redis-slave-1
    ports:
      - 6380:6380
    volumes:
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-slave1.conf:/redis.conf
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-slave1/data:/data
    command: bash -c "redis-server /redis.conf  --slaveof 172.16.150.55 6379"
    depends_on:
      - redis-master
    networks:
      - redis-sentinel-1

  redis-slave-2:
    image: redis:6.0.9
    container_name: redis-slave-2
    ports:
      - 6381:6381
    volumes:
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-slave2.conf:/redis.conf
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-slave2/data:/data
    command: bash -c "redis-server /redis.conf --slaveof 172.16.150.55 6379"
    depends_on:
      - redis-master
    networks:
      - redis-sentinel-1

  redis-sentinel-1:
    image: redis:6.0.9
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    volumes:
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-sentinel1/data:/data
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-sentinel-1.conf:/etc/sentinel.conf
    command: bash -c "redis-sentinel /etc/sentinel.conf && chmod 777 /etc/sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-sentinel-1

  redis-sentinel-2:
    image: redis:6.0.9
    container_name: redis-sentinel-2
    ports:
      - 26380:26380
    volumes:
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-sentinel2/data:/data
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-sentinel-2.conf:/etc/sentinel.conf
    command: bash -c "redis-sentinel /etc/sentinel.conf && chmod 777 /etc/sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-sentinel-1

  redis-sentinel-3:
    image: redis:6.0.9
    container_name: redis-sentinel-3
    ports:
      - 26381:23681
    volumes:
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-sentinel3/data:/data
      - C:/Users/cesh1/Desktop/gitee/wq-alg/src/main/java/org/redis2/redis-sentinel-3.conf:/etc/sentinel.conf
    command: bash -c "redis-sentinel /etc/sentinel.conf && chmod 777 /etc/sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-sentinel-1
